CHANGES.rst
persistent/_compat.h
persistent/_compat.py
persistent/cPersistence.c
persistent/persistence.py
persistent/tests/test_persistence.py

Implementation of the feature discussed in zopefoundation/persistent#15
I'd appreciate a close review of the C implementation. It's based on code in cPickle (https://github.com/python/cpython/blob/master/Modules/_pickle.c#L5956) but I'm just pretending to know what I'm doing with pointers and with refcounting.

Intern keys in `__setstate__`

---

.travis.yml
persistent/tests/test_persistence.py

(by disabling the test, since pypy3 doesn't guarantee identity of intern'd strings)
Not using unittest.skipIf because it doesn't exist in python 2.6.
Also enable travis tests for 3.4 and pypy3

fix test___setstate___interns_dict_keys failure on pypy3

---

CHANGES.rst
persistent/tests/test_timestamp.py
persistent/timestamp.py

It turns out that the Python version was rounding the seconds where the C version was doing nothing so complicated.
Also, make the behaviour of comparisons and hashing match as well. This should all be tested.
Fixes zopefoundation/persistent#18. Relates to zopefoundation/ZODB#33 and fixes at least some of the issues there (there will probably be more PRs coming for the rest).

Make the .raw() and repr() of the Python TimeStamp match the C version in more cases.

---

CHANGES.rst
tox.ini

The `none-any` wheels built in the PURE_PYTHON environments should not poison the user's global wheel cache.

Don't use/poison global wheel cache when building w/ PURE_PYTHON.

---

persistent/tests/test_timestamp.py
persistent/timestamp.py

The fractional part of return values was always 0.

TimeStamp: sub-second precision for Python implementation of timeTime()

---

persistent/cPersistence.c
persistent/persistence.py
persistent/tests/test_persistence.py

On ._p_deactivate() and ._p_invalidate(), when an object goes to ghost
state, objects referenced by all its attributes, except related to
persistence machinery, are released, this way freeing memory (if they
were referenced only from going-to-ghost object).
That's the idea - an object in ghost state is simply a stub, which loads
its content on first access (via hooking into get/set attr) while
occupying minimal memory in not-yet-loaded state.
However the above is not completely true right now, as currently on
ghostification only object's .__dict__ is released, while in-slots objects
are retained attached to ghost object staying in RAM:
---- 8< ----
from ZODB import DB
from persistent import Persistent
import gc
db = DB(None)
jar = db.open()
class C:
def __init__(self, v):
self.v = v
def …

On deactivate release in-slots objects too

---

persistent/tests/test_timestamp.py
persistent/timestamp.py

In order to work with max integers, persistent uses ctypes. It is not really necessary but breaks compatibility with pypy.js, for example.

Get rid of ctypes dependency to make persistent more pure-python compatible

---

persistent/persistence.py
persistent/tests/test_persistence.py

fe2219f4 (On deactivate release in-slots objects too) started to release
objects from slotted variables but was not careful enough while doing so: we
have to be careful while deleting as for unset variables it will raise
AttributeError:
```
class C(object):
__slots__ = ['aaa', 'unset']
def __init__(self, aaa):
self.aaa = 1
c = C(111)
del c.aaa
del c.unset
Traceback (most recent call last):
File "y.py", line 9, in <module>
del c.unset
AttributeError: unset
```
Caught by preparing fix for https://github.com/zopefoundation/persistent/pull/44#issuecomment-256768600
C version already have this protection in the original fe2219f4 patch:
```
+            if (PyObject_GenericSetAttr((PyObject *)self, name, NULL) < 0)
+                /* delattr of non-set slot will raise AttributeError - we
+ …
```

py/deactivate vs slots: A slot variable could not be initialized at all

---

CHANGES.rst
persistent/tests/test_timestamp.py
persistent/timestamp.py

Fixes #51
Part of the problem was in the tests. The detection of when the hash
gets truncated was broken on win32.
Part of the problem is somewhere in the _wraparound function, I think,
because even fixing the tests to use the right values we still get
mismatches. Rather than dig into that, I just go back to using ctypes
when it's available.

Fix Python timestamp hash on 64-bit windows

---

.gitignore
CHANGES.rst
persistent/persistence.py
persistent/picklecache.py
persistent/tests/test_persistence.py
persistent/tests/test_picklecache.py

Fixes #49. Tested with ZODB, ZEO, zope.container.
(Includes #47 , rebased on master and tested with PyPy on ZEO and ZODB, because when I created this branch I expected that PR to be merged already by the time this was ready.)

new_ghost shouldn't clear newargs (PyPy consistent with C)

---

.travis.yml

Added at the top to see if it would change the build order. Turns out it doesn't, they're grouped by OS and the linux builds go first (and faster). (I would move it down with the others, but then there'd have to be another build and it's taking more than an hour now for the mac builds to start.)

Python 3.6 Mac

---

.travis.yml

Ref #58. This should get us the right wheel tags and hopefully the non-floating 3.6 build (until 'multibuild' from terryfy is updated we have to use a specific 3.6.0 version).
Fingers crossed.
EDIT: I forgot zope.interface from the list of things with C extensions.
EDIT2: Oh, and I guess zope.index has an *optional* extension.

Use macpython for all Mac builds.

---

CHANGES.rst
persistent/cPersistence.c
persistent/tests/test_persistence.py

PR #52 introduced a code path to `ghostify` that calls PyErr_Clear() with the intent to avoid propagating `AttributeErrors` for slots.
However, if there is an error (like a POSKeyError) raised by jar.setstate(), then `unghostify` will call `ghostify` with an error pending. If the object had slots that weren't set and the `AttributeError` was cleared, so was the pending error from setstate. So when `ghostify` returned NULL that got propagated up to the interpreter which finds no exception and so raises `SystemError: error
return without exception set`.
This commit makes `unghostify` save and restore the exception state around the call to `PyErr_Clear` so the *real* exception is raised, rather than the baffling and unhelpful SystemError.

Avoid raising a SystemError when clearing slots if setstate() failed.

---

CHANGES.rst
persistent/cPickleCache.c

Instead of testing object sizes.
This matches what the pure Python implementation does and is a stronger test that the object really is compatible with the cache. Previously, an object could potentially include ``cPersistent_HEAD``
and *not* set ``tp_base`` to ``cPersistenceCAPI->pertype`` and still be eligible for the pickle cache; that is no longer the case.
This resolves several compiler warnings:
```
persistent/cPickleCache.c:521:43: warning: comparison of integers of different signs: 'Py_ssize_t' (aka 'long') and 'unsigned long' [-Wsign-compare]
(v->ob_type->tp_basicsize >= sizeof(cPersistentObject))
~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
persistent/cPickleCache.c:709:39: warning: comparison of integers of different signs: 'Py_ssize_t' (aka 'long') and 'unsigned long' …
```

Change cPickleCache to use PER_TypeCheck

---

.coveragerc
.manylinux-install.sh
.travis.yml
appveyor.yml
persistent/tests/test_picklecache.py
setup.cfg
setup.py
tox.ini

Both are essentially deprecated. This is a step in producing usable coverage numbers.
Since we support PURE_PYTHON at runtime, always build the C extensions on supported platforms so that they go in the wheel. This avoids any issue with polluting the wheel cache.
(Also remove cp33 from the manylinux build. This was missed in https://github.com/zopefoundation/persistent/pull/74)

Switch to zope.testrunner from 'python setup.py test' and 'nose'.

---

.coveragerc
.travis.yml
CHANGES.rst
README.rst
docs/api/attributes.rst
docs/api/cache.rst
docs/api/pickling.rst
persistent/__init__.py
persistent/_compat.py
persistent/interfaces.py
persistent/list.py
persistent/persistence.py
persistent/tests/attrhooks.py
persistent/tests/cucumbers.py
persistent/tests/test_docs.py
persistent/tests/test_list.py
persistent/tests/test_mapping.py
persistent/tests/test_persistence.py
persistent/tests/test_picklecache.py
persistent/tests/test_ring.py
persistent/tests/test_timestamp.py
persistent/tests/test_wref.py
persistent/tests/utils.py
persistent/timestamp.py
persistent/wref.py
setup.py
tox.ini

In tox only for now, coveralls coming in a followup PR or commit.
There are also two minor pure-python bug fixes I discovered.
Addresses #76.

Reach 100% coverage

---

CHANGES.rst
persistent/_compat.py
persistent/tests/test_persistence.py
persistent/tests/test_picklecache.py
persistent/tests/test_wref.py

Also some minor DRY in test_picklecache.py
Fixes #81.
Currently based on #80 so that I could have coverage numbers 😄 Only the final commit is relevant.

 Remove unneeded _compat._b/_u/_native.

---

CHANGES.rst
docs/using.rst
persistent/cPersistence.c
persistent/interfaces.py
persistent/persistence.py
persistent/tests/test_persistence.py

As specified in #11. See the tests for what the output looks like; in the usual case it will be something like `"<persistent.Persistent object at 0xdeadbeef oid b'12345678' in <SomeJar>>"`
I would appreciate a thorough check of the C code, I'm not a C API expert.

Include OID and jar in default repr of Persistent; let subclasses implement _p_repr for exception safety

---

CHANGES.rst
persistent/tests/test_timestamp.py
persistent/timestamp.py

Fixes #41.
The C version now always rounds its seconds value, even when its decoding from a value with lots of noise, as when initially created from 6.123456789. Previously it would return 6.1234567780047655; now it returns 6.123457 which is what it would return after being round-tripped through raw().
The Python version also does this, by (expensively) unpacking the raw value it just computed.
These could both probably be better optimized.

Make the C and Python TimeStamp round the same way

---

CHANGES.rst
persistent/_timestamp.c
persistent/timestamp.py

This *might* fix #86? (*waves hands* by avoiding mixing signed and unsigned operations)
I personally find that it makes the data derivation/reconstruction more clear by making the powers-of-two factors more obvious. (The two smaller values were clear to me, but without punctuation it wasn't immediately obvious to me that 16777216 = 16,777,216 = 0x1000000 = 2^24.)
(Tested locally on 64-bit, relying on Appveyor CI for 32-bit tests.)

Use unsigned constants for second arithmetic in C timestamp

---

persistent/tests/test_docs.py

I used to get failures like
py27 runtests: commands[0] | zope-testrunner --test-path=.
Test-module import failures:
Module: persistent.tests.test_docs
IOError: [Errno 2] No such file or directory: '/home/mg/src/zopefoundation/persistent/.tox/docs/api/cache.rst'
Running zope.testrunner.layer.UnitTests tests:
Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
Ran 524 tests with 0 failures, 1 errors and 0 skipped in 0.249 seconds.
Tearing down left over layers:
Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
Test-modules with import problems:
persistent.tests.test_docs
ERROR: InvocationError for command '/home/mg/src/zopefoundation/persistent/.tox/py27/bin/zope-testrunner --test-path=.' (exited with code 1)
because adding a ../ at the end of the path is not the same as …

Make test pass when run with 'tox'

---

.travis.yml
CHANGES.rst
persistent/_timestamp.c

This should fix #86
Run a compiler with wrapv turned off to verify this.

Explicitly use unsigned hex literals when [un]packing timestamps.

---

CHANGES.rst
persistent/cPersistence.c
persistent/persistence.py
persistent/tests/test_persistence.py

Fixes #95
Built on #97 as they touch the same code.

Always format 8-byte oids as ints in hexadecimal.

---

CHANGES.rst
persistent/cPersistence.c
persistent/persistence.py
persistent/tests/test_persistence.py

Fix the repr of the persistent objects to include the module name when using the C extension. This matches the pure-Python behaviour and the behaviour prior to 4.4.0.
Do so by getting the `__module__` and `__name__` attributes of the type, just like the Python version. Credit to @mgedmin for the suggestion.
Fixes #92

Include the module in the C repr

---

MANIFEST.in
setup.py

Fixes #99 
`bdist_wheel` isn't guided by the MANIFEST, only sdists are. So we have to specify what packages to include in setup.py, which is what guides bdist_wheel.

Exclude the 'terryfy' directory from wheels and sdists

---

CHANGES.rst
persistent/__init__.py
persistent/cPickleCache.c
persistent/interfaces.py
persistent/picklecache.py
persistent/tests/test_picklecache.py

Fix discrepancies between it and the Python implementation:
- The C implementation now raises ``ValueError`` instead of ``AssertionError`` for certain types of bad inputs.
- The Python implementation uses the C wording for error messages.
- The C implementation properly implements ``IPickleCache``; methods  unique to the Python implementation were moved to ``IExtendedPickleCache``.
- The Python implementation raises ``AttributeError`` if a  persistent class doesn't have a ``p_jar`` attribute.
Fixes #102

Fully test the C implementation of the PickleCache

---

CHANGES.rst
persistent/cPickleCache.c
persistent/picklecache.py
persistent/tests/test_picklecache.py

Hello. This PR is for zopefoundation/ZODB#231 . cache_size_bytes works with cache_size=0,  no need to set cache_size to a large value.

Allow sweeping cache without cache_size and with cache_size_bytes only.

---

docs/api/attributes.rst
docs/api/cache.rst
docs/api/pickling.rst
docs/glossary.rst
docs/using.rst

Found some typos in the docs.
REVIEWER: please pay attention to the cache.rst doc. On the first Note, I assumed that the author intended to say: "... newly created and **initialized** objects directly ... " instead of "... **uninitialized** ..."

Fix some typos in docs.

---

CHANGES.rst
persistent/ring.py
persistent/tests/test_persistence.py
persistent/tests/test_picklecache.py
persistent/tests/test_ring.py
persistent/tests/test_timestamp.py
setup.py
tox.ini

Require CFFI on CPython for pure-Python operation.

---

persistent/_timestamp.c
persistent/cPersistence.c

This API was introduced in Python 2.5 and the old one (using ints) has been deprecated since Python 3.8.
Fixes #108.
Somebody who actually knows the Python C API please review this, because I just pretend I know C.

Use Py_ssize_t for length arguments of PyArg_ParseTuple

---

.manylinux-install.sh
appveyor.yml

Since 3.8 is not available on Appveyor yet, use a script to install it.
Meant to fix #117 eventually.

Enable Python 3.8 on Appveyer and also for manylinux builds

---

.manylinux-install.sh
.manylinux.sh
.travis.yml

- Try manylinux builds on every commit so we can discover breakages in advance
- Fix manylinux builds so they actually work (i.e. don't upgrade wheel to latest version, which is incompatible with auditwheel)
- Add pretty names to Travis build matrix rows
Should fix #113.
The diff is messy, for which I apologize. I had to reformat the YAML to understand it.
Drop dist: xenial which has become the default.
Rename matrix: to jobs: because that's the preferred spelling according to Travis CI docs.
Move regular Linux Python builds outside build matrix, for conciseness (unfortunately this means 3.6 builds are now done twice: once without -fwrapv and once with).
Move docker pull and twine upload out of .manylinux.sh and into .travis.yml. (The docker pull mostly because we need to override the …

Fix manylinux wheel builds and build them always

---

.travis.yml

Terrify now supports building py3.8 on mac os.

terrif now supports py3.8 builds on mac

---

.travis.yml

Our Python 3.6 builds on MacOS started failing with a
> Couldn't use data file '/Users/travis/build/zopefoundation/persistent/.coverage': Safety level
may not be changed inside a transaction
error from `coverage run`, after the test suite is done and it's time to collate and store coverage data.  This is probably caused by a new release of coverage.py (5.0.3; the last successfull built had coverage 4.5.4) that uses sqlite for .coverage and is reported upstream as https://github.com/nedbat/coveragepy/issues/703.
Other platforms and other Python versions do not have this problem.  Other platforms use a newer Python 3.6.x dot release, while MacOS is pinned to 3.6.0.
This PR is an experiment to see if a different Python 3.6.x dot release helps.  Turns out it does!
We have a few other …

Use Python 3.6.2 on MacOS

---

.travis.yml
CHANGES.rst
persistent/list.py
persistent/mapping.py
persistent/tests/test_list.py

The inherited `clear()` method in UserList can modify the `PersistentList` without causing the object to be marked as changed. This patch causes the `clear()` method to mark the object as changed.

FIX: Clearing a persistent list does not mark it as changed.

---

CHANGES.rst
persistent/mapping.py
persistent/tests/test_list.py
persistent/tests/test_mapping.py
persistent/tests/utils.py

Like the native ``UserDict``. Previously, most uses of keyword arguments resulted in ``TypeError``; in the undocumented and extremely unlikely event of a single keyword argument called ``b`` that happens to be a dictionary, the behaviour will change. Also adjust
the signatures of ``setdefault`` and ``pop`` to match the native version.
Also optimize `clear` and `popitem` to not mark the object as changed unnecessarily.
Fixes #126

Fix PersistentDict.update to accept keyword arguments.

---

CHANGES.rst
persistent/cPersistence.c
persistent/cPickleCache.c
setup.py

There are three commits showing the iterations I went through.
- The first commit adds the necessary preprocessor magic to make the extension build and run on 3.9.0a3+.
- The second commit adds more preprocessor magic to make it build and run on 3.9.0a3 if `Py_TRACE_REFS` is actually defined.
- The third commit removes all usage of those internal functions entirely, after I verified that everything still worked on the `Py_TRACE_REFS` build.
Rationale to remove usage of the internal functions:
- They're documented specifically as only to be used by the core interpreter.
- The nesting of conditions to make them work was pretty ugly.
- Especially since the core logic of the function is already "hairy."
- It was not at all clear to me that they were actually doing the right thing anymore …

Fix issue 124

---

persistent/_compat.h

Fixes #125
Because it was just an alias for the documented API, there should be no repercussions. The exception (and the reason for this issue in the first place) is if something both includes 'cPersistence.h' and also defines their own INT_AS_LONG macro. If the definitions differ, the compiler might now emit a warning. I [saw that in BTrees]( https://github.com/zopefoundation/BTrees/pull/122/files#diff-277c29c35c8feb60719e5ec94a3fe72e)

Python3: Stop using undocumented PyLong_AS_LONG.

---

CHANGES.rst
persistent/list.py
persistent/mapping.py
persistent/tests/test_list.py
persistent/tests/test_mapping.py
persistent/tests/utils.py

See https://bugs.python.org/issue27639 and https://bugs.python.org/issue27141
Fixes #112

Fix slicing and copying of PersistentList and PersistentMapping.

---

.travis.yml
CHANGES.rst
appveyor.yml
persistent/__init__.py
persistent/_compat.py
persistent/cPersistence.c
persistent/interfaces.py
persistent/persistence.py
persistent/picklecache.py
persistent/tests/test__compat.py
persistent/tests/test_persistence.py
persistent/tests/test_picklecache.py
persistent/tests/test_timestamp.py
persistent/tests/utils.py
persistent/timestamp.py
setup.py
tox.ini

With PURE_PYTHON=0, like in zope.interface.
Also always require all three extensions. This solves mysterious issues you can get if you wind up mixing and matching (#124).
Fixes #131
Add travis and tox tests for this.

Add the ability to force use of C extensions.

---

CHANGES.rst
persistent/_ring_build.py
persistent/cPersistence.h
persistent/persistence.py
persistent/picklecache.py
persistent/ring.c
persistent/ring.h
persistent/ring.py
persistent/tests/test_persistence.py
persistent/tests/test_picklecache.py
persistent/tests/test_ring.py
persistent/tests/utils.py

Except on PyPy, where we can already weakref them automatically. On CPython, track them using their `id` (can't use an `ffi.new_handle` "pointer" because it strongly references the object it's a handle for).
Fixes #133.

Use ffi.gc() on the ring nodes to avoid needing a weakref to PersistentPy

---

CHANGES.rst
persistent/mapping.py
persistent/tests/test_mapping.py

If there's no jar, we can't be _p_changed.
Fixes #139.

Remove faulty assertion in PersistentMapping.clear().

---

CHANGES.rst
persistent/_ring_build.py
persistent/ring.py

Add change note.
Fixes #137
Supersedes and fixes #141 for committer agreement purposes.

Use unsigned integers to represent addresses

---

CHANGES.rst
persistent/tests/test_picklecache.py

Fix a test failure against zope.interface5 due to overly specific exception tests.

---

CHANGES.rst
persistent/cPersistence.c
persistent/cPickleCache.c

Fixes #143
Based on #145 (to avoid the guaranteed conflict in CHANGES.rst), only the last commit is relevant.

 Fix two reference leaks that could occur following an obscure error

---

setup.cfg

We use the CI to build and upload binary wheels.
Binary wheels built on individuals' machines may use CFLAGS, etc, that are not compatible with all machines, but this is not expressed in the wheel tags. Thus, incompatible machines may download and install such wheels, leading to bad behaviour or even Illegal Instruction crashes.
Fixes #154.
Also set the long_description_content_type to avoid getting warnings from 'twine check'.

Ask zest.releaser not to upload binary wheels.

---

CHANGES.rst
persistent/cPersistence.c
persistent/persistence.py
persistent/tests/test_persistence.py

By activating the object.
Add tests for this.
In the process of adding tests, I discovered the mock pickle cache used by the Python tests was returning the wrong thing from new_ghost (not a ghost), so I fixed this and added some extra tests and assertions to be sure the behaviour matches with the real and C caches.
Fixes #155

Make the Python impl handle setting __class__ and __dict__ on ghosts like C

---

CHANGES.rst
persistent/picklecache.py
persistent/tests/test_picklecache.py

Only affects CPython when PURE_PYTHON=1.
Add tests for this. They're a bit dicey because this is a hard situation to get into, but they do test the symptoms.
Fixes #150

Fix the CFFI cache implementation to not print AttributeErrors.

---

CHANGES.rst
persistent/picklecache.py
persistent/tests/test_picklecache.py

This fixes hard-to-debug ZODB ConnectionStateError cases with persistent zope.component registrations on PyPy.
I tried to come up with a test that would also fail on CPython using circular references, but did not succeed (because part of evicting objects is clearing their dict, breaking the reference cycle).
Fixes #149. Well, band-aids it anyway. I'd like to think of a better way (the assumption that weakrefs are cleared immediately is pretty baked-in to zope.interface, at least when used with ZODB).
Currently based on #161 to avoid conflicts; only the last commit is relevant.

Make the Python PickleCache run a GC when it evicts weakly-referenced objects.

---

.github/workflows/tests.yml
.manylinux-install.sh
.meta.toml
CHANGES.rst
src/persistent/tests/test_compile_flags.py
tox.ini

Add a regression test for CFLAGS not having -Ofast, which is known to break things.  See https://github.com/zopefoundation/meta/pull/155 for reference.
For some reason I was unable to verify that the CFLAGS problem actually affects `persistent`.  Running the new regression test with
```
$ CFLAGS=-Ofast tox -re py38 -- -pvc -m test_compile_flags
```
did not cause a failure.

Update to the latest c-code template

---

CHANGES.rst

The new test checking against the `-Ofast` problem was failing on `master`.
I cleaned the caches using
```
repo=persistent;gh api -H "Accept: application/vnd.github+json" /repos/zopefoundation/$repo/actions/caches|jq -r .actions_caches[].key|sort -u|grep Linux-pip-|xargs -I{} gh api -H "Accept: application/vnd.github+json" --method DELETE /repos/zopefoundation/$repo/actions/caches?key={}
```
Rerunning the failed jobs on `master` was not enough, so I am doing a complete re-run here.

Trigger GHA after deleting its caches.

---

.github/workflows/tests.yml
.manylinux-install.sh
.meta.toml
CHANGES.rst
appveyor.yml
tox.ini

Depends on https://github.com/python-cffi/cffi/issues/23 ~~and its release in a version of `cffi` > 1.16.~~ we are now using an unreleased version with https://github.com/zopefoundation/meta/pull/227

Add preliminary support for Python 3.13a1

---

setup.py
src/persistent/_compat.py
src/persistent/_ring_build.py
src/persistent/dict.py
src/persistent/interfaces.py
src/persistent/list.py
src/persistent/mapping.py
src/persistent/persistence.py
src/persistent/picklecache.py
src/persistent/ring.py
src/persistent/tests/attrhooks.py
src/persistent/tests/cucumbers.py
src/persistent/tests/test__compat.py
src/persistent/tests/test_list.py
src/persistent/tests/test_mapping.py
src/persistent/tests/test_persistence.py
src/persistent/tests/test_picklecache.py
src/persistent/tests/test_ring.py
src/persistent/tests/test_timestamp.py
src/persistent/tests/test_wref.py
src/persistent/tests/utils.py
src/persistent/timestamp.py
src/persistent/wref.py

After fixing isort it got visible that we did not do this, yet.

Flake8 the code.

---

.github/workflows/tests.yml
.meta.toml

Created via https://github.com/zopefoundation/meta/pull/236.
The changes of the os versions are because this is not yet on master. This PR is mostly to show that https://github.com/zopefoundation/meta/pull/236 does not delete the cffi installation.

Require cffi from meta/config

---

.coveragerc
.github/workflows/tests.yml
.manylinux-install.sh
.meta.toml
tox.ini

Also see https://github.com/zopefoundation/meta/issues/235

Update meta/config template to publish Windows wheels to PyPI

---

src/persistent/_compat.h

The '#else' would've actually bound to the '#ifndef' at the top of the module, resulting in breakage if the header ever got included multiple times.

fix: remove '#else' and following Py2 definitions

---

CHANGES.rst
src/persistent/cPickleCache.c

These assertions failed to compile if built without `-DNDEBUG`.  As of setuptools 75.7.0, setting `CFLAGS` to anything while building an extension no longer copies the `CFLAGS` that Python itself was built with, so `NDEBUG` is less likely to be defined.  See https://github.com/pypa/setuptools/issues/4836 and https://bugs.debian.org/1098602.

Use Py_REFCNT to access cPersistentObject refcounts

---

CHANGES.rst
src/persistent/cPersistence.c
src/persistent/persistence.py
src/persistent/tests/test_persistence.py

Display oids in same format as ZODB.utils.oid_repr

---

.github/workflows/tests.yml
.manylinux-install.sh
.meta.toml
.pre-commit-config.yaml
CHANGES.rst
pyproject.toml
src/persistent/cPersistence.c
tox.ini

Fix: https://github.com/zopefoundation/persistent/issues/218
IMHO in python 3.14 dictionary and/or garbage optimization requires to explicitly clear the dictionary.
Although this change seems to fix the tests in python 3.14 (tested with python 3.14.0b2), I suggest double-checking the change with someone more familiar with the internals of the library to exclude any side effects related to the change

Clear dict py314

---

CHANGES.rst
setup.py

Closes #222
CFFI does not support pyproject.toml yet, instructions and prerequisites for building CFFI extension modules must stay in setup.py for now.

Fix cffi extension build configuration
